openapi: "3.0.0"
info:
  description: "This is the API for the upgrade campsite service."
  version: "1.0.0"
  title: "Upgrade Campsite Rest API"
  contact:
    email: "serge.nassar@gmail.com"
tags:
  - name: "Campsite"
    description: "Campsite operations"
paths:
  /v1/campsites/:
    get:
      tags:
        - "Campsite"
      summary: "Get the list of campsites."
      description: "Returns the list of campsites."
      operationId: "getCampsites"
      responses:
        "200":
          description: "Campsites found."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Campsite"
        "404":
          description: "Campsites not found."
        "503":
          description: "Internal error retrieving campsites."
  /v1/campsites/{campsiteId}:
    get:
      tags:
        - "Campsite"
      summary: "Get the campsite by id."
      description: "Returns a campsite matching the id"
      operationId: "getCampsite"
      parameters:
        - name: "campsiteId"
          in: "path"
          description: "UUID of the campsite."
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Campsite found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Campsite"
        "400":
          description: "Invalid input data."
        "404":
          description: "Campsite not found."
        "503":
          description: "Internal error retrieving campsite."
components:
  schemas:
    Campsite:
      type: "object"
      properties:
        campsiteId:
          type: "string"
          format: "uuid"
        name:
          type: "string"
