eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST:http://127.0.0.1:8761}/eureka/
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: upgradeuser
    password: upgrade123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
